---
title: "Get BRFSS Data"
author: "Brian High"
date: "02/17/2016"
output:
  html_document:
    keep_md: yes
---

## Overview

Get the 2012-2014 datasets from http://www.cdc.gov/brfss, load into a data 
table, and report file sizes and memory use along the way to track progress 
and resource utilization.

## Configure the time range in years

```{r}
datayears <- as.character(seq(2012, 2014))
```

## Load packages

```{r, message=FALSE}
## Install packages (if necessary)
for (pkg in c("foreign", "data.table", "plyr")) {
    if (! suppressWarnings(require(pkg, character.only=TRUE)) ) {
        install.packages(pkg, repos="http://cran.fhcrc.org", dependencies=TRUE)
        if (! suppressWarnings(require(pkg, character.only=TRUE)) ) {
            stop(paste(c("Can't load package: ", pkg, "!"), sep = ""))
        }
    }
}
```

## Set up data folder

```{r}
# Create the data folder if it does not already exist
datadir <- "./data"
dir.create(file.path(datadir), showWarnings=FALSE, recursive=TRUE)

# Enter data folder, first saving location of current folder
projdir <- getwd()
setwd(datadir)
datadir <- getwd()
```

## Download data files

```{r}
getDataURL <- function(datayear) {
    # Correct for change in URLs after the year 2010
    if (as.numeric(datayear) > 2010) {
        dataurl <- paste("http://www.cdc.gov/brfss/annual_data/", datayear, 
                         "/files/LLCP", datayear, "XPT.ZIP", sep="")
    } else {
        dataurl <- paste("http://www.cdc.gov/brfss/annual_data/", datayear, 
                         "/files/CDBRFS", substr(datayear, 3, 4), "XPT.ZIP", 
                         sep="")        
    }
    return(dataurl)
}

reportFileSize <- function(filename) {
    # Report file size in MB. file.size() does not work in Windows.
    if (Sys.info()[['sysname']] != "Windows") {
        cat(paste(c("Size of file", filename, "is", 
                round(file.size(filename) / 1024 /1024, 1), "MB", "\n")))
    }
}

downloadDataFile <- function(datadir, datayear) {
    setwd(datadir)
    dataurl <- getDataURL(datayear)
    datafile <- paste("LLCP", datayear, "XPT.ZIP", sep="")
    
    if (! file.exists(datafile)) {
        cat("Downloading data file for year", datayear, "...\n")
        download.file(dataurl, datafile, mode='wb')
        cat("Completed at", Sys.time(), "\n")
    }
    
    # Report file size of downloaded file
    retval <- reportFileSize(datafile)
    
    # Return to project folder
    setwd(projdir)
}

retval <- sapply(datayears, function(x) downloadDataFile(datadir, x))
```

## Extract data files

```{r}
getSASFileName <- function(datayear) {
    # Correct for change in filenames after the year 2010
    if (as.numeric(datayear) > 2010) {
        sasfile <- paste("LLCP", datayear, ".XPT", sep="")
    } else {
        sasfile <- paste("CDBRFS", substr(datayear, 3, 4), ".XPT", sep="")
    }
    
    return(sasfile)
}

extractDataFile <- function (datadir, datayear) {
    setwd(datadir)
    sasfile <- getSASFileName(datayear)
    datafile <- paste("LLCP", datayear, "XPT.ZIP", sep="")
    
    if (! file.exists(sasfile)) {
        cat("Extracting SAS data file ", sasfile, "...", "\n")
        unzip(datafile)
        # Remove the space character at the end of filename if necessary.
        # This found to be an issue in the 2014 data file.
        if (file.exists(paste(sasfile, " ", sep=""))) {
            file.rename(from = paste(sasfile, " ", sep=""), to = sasfile)
        }
    }
    
    # Report file size of extracted file
    retval <- reportFileSize(sasfile)
    
    # Return to project folder
    setwd(projdir)
}

retval <- sapply(datayears, function(x) extractDataFile(datadir, x))
```

## Read data files into R data table

```{r}
reportSize <- function(dt, datayear) {
    # Report data table size and dimensions
    cat("Size of data table for", datayear, "is:\n")
    print(object.size(dt), units = "MB")
    cat("Data table for", datayear, "contains", 
        dim(dt)[1], "observations and", 
        dim(dt)[2], "variables", "\n")
    return(NULL)
}

importDataFile <- function(datadir, datayear) {
    # Read data file
    setwd(datadir)
    options(digits=2)
    sasfile <- getSASFileName(datayear)
    dt <- as.data.table(read.xport(sasfile))
    retval <- reportSize(dt, datayear)
    
    # Return to project folder
    setwd(projdir)
    return(dt)
}

brfss <- as.data.table(adply(.data=datayears, .margins=c(1),
                       .fun=function(x) importDataFile(datadir, x)))
retval <- reportSize(brfss, "all years")
```

## Write data to a CSV file

```{r warning=FALSE}
csvfile <- paste(datadir, "brfss.csv", sep="/")
write.table(x=brfss, file=csvfile, row.names=F, fileEncoding="UTF-8", 
            sep=",", quote=T, qmethod="escape", eol="\n")

# Report file size of CSV file
retval <- reportFileSize(csvfile)
```
